services:
  db:
    image: postgres:15
    container_name: Cities-Container
    restart: always
    environment:
      POSTGRES_DB: cities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data: